# Generated by Django 2.2.5 on 2019-09-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ImageField(upload_to='1')),
                ('dispose', models.ImageField(upload_to='2')),
                ('time', models.DateField(auto_now_add=True)),
                ('username', models.CharField(max_length=32)),
            ],
        ),
    ]
