# Generated by Django 2.2.4 on 2019-09-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ImageField(upload_to='1')),
                ('seg', models.CharField(max_length=128)),
                ('det', models.CharField(max_length=128)),
                ('sty', models.CharField(max_length=128)),
                ('operation', models.CharField(max_length=32)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=32)),
            ],
        ),
    ]
